### ISSUE TITLE
Config Fire for some variables

### ISSUE THREAD

**Issue by dheil** [AcuGIS/OpenTileServer#10]
Hi, 
have you thought about using a config file to set some more variables so the user does not have to edit the installation script? 
I had to change/set the database name for example. Also the ssl / pbf links etc could also be set in that config file - just a thought. Beside this little issue the script is very nice and helped saving a lot of time ;)

**Comment by DavidGhedini** [comment]
Glad the script is useful.  Ill look at adding a config file.
