### ISSUE TITLE
"error while opening file 1"

### ISSUE THREAD

**Issue by pommesmensch** [AcuGIS/OpenTileServer#15]
Hey! :)

I´m trying to install opentileserver on a freshly installed ubuntu 14.04 server.
I execute the following command as root (testing in a vm):

`./opentileserver.sh web carto http://download.geofabrik.de/north-america-us/delaware-lates.osm.pbf` (exactly copied from your website)

and get the result:
`Reading in file: 1
error while opening file 1`

with tons of notices, that tables doesnt exists (all of them):

Setting up table: planes_osm_rels
NOTICE: table "planet_osm_rels" does not exist, skipping

Any idea what i could try? :)

Kind regards,

pommes

**Comment by DavidGhedini** [comment]
The url is:  http://download.geofabrik.de/north-america/us/delaware-latest.osm.pbf
You can view all of the extracts as well as get urls vie GeoFabrik at:
http://download.geofabrik.de/

**Comment by pommesmensch** [comment]
Hey David,
thank you very much for your really fast response! 

I used the correct URL, but made this mistake while copying it into github. Sorry for that! :(
