### ISSUE TITLE
Error with Web mod SSL

### ISSUE THREAD

**Issue by RS974** [AcuGIS/OpenTileServer#17]
Hi,

I don't use Ubuntu, so i use your script for simplicity.
I install une clean Ubuntu and i run the script (opentileserver.sh ssl bright URI).
But i had an error.

Updating lat,long for france in Leaflet...
Lat/Long for france set to 46.2276380,2.2137490
Generating RSA private key, 1024 bit long modulus
............................................................++++++
.....++++++
e is 65537 (0x10001)
writing RSA key
chown: invalid user: 'apache:apache'

User and Group don't exist.
All subfolder in /etc/apache2 is root:root

Thanks in advance :)

**Comment by DavidGhedini** [comment]
Please try to chown to www-data user.

**Comment by RS974** [comment]
I confirm www-data user exists.
I modified the script and restart it
