### ISSUE TITLE
Variables aren't used or undefined ?

### ISSUE THREAD

**Issue by RS974** [AcuGIS/OpenTileServer#19]
Hi,

I will have some questions

1>> I change OSM_USER (line 22), is it a mistake?

Line 136 "export WORKDIR_OSM=/home/${OSM_USER}/.osmosis"
Line 139 "echo 'export WORKDIR_OSM=/home/tile/.osmosis' >> /etc/environment"

I replace Line 139 by "echo 'export WORKDIR_OSM=/home/'${OSM_USER}'/.osmosis' >> /etc/environment"

2>> OSM_PG_PASS is created in opentileserver.sh
It is also used reload-opentileserver.sh but there is no value.

3>> The /etc/cron.daily/osm-update.sh file was created but is empty.
I wanted to fill in manually, but from where comes the variable MAPFIG_PG_PASS

echo or cat ?
"echo >/etc/cron.daily/osm-update.sh <<CMD_EOF" ==> "cat >/etc/cron.daily/osm-update.sh <<CMD_EOF"

Thanks.

**Comment by DavidGhedini** [comment]
Sorry, I have been on vacation. Looking at this now...

**Comment by DavidGhedini** [comment]
This was changed from echo to cat now.  Thanks for above.
