### ISSUE TITLE
Good work

### ISSUE THREAD

**Issue by webmap2015** [AcuGIS/OpenTileServer#2]
1. When I run "opentileserver.sh" script with carto style, there is an error in "./get-shapefiles.sh" script line 15. So, you need to add "curl" package.
2. Up to zoom 18, working good but in zoom 19, there is no tiles. But, "www.openstreetmap.org" website has up to zoom 19 tiles.
3. I can use only max 12 CPU with "osm2pqsql". Could you increase it?
4. There are only two styles (carto, bright). Could you add below style ?

OpenCycleMap
Mapquest
Thunderforest Tiles
CartoDB Positron and Dark Matter
Stamen Design

Thanks.

**Comment by DavidGhedini** [comment]
Thanks.
It pulls down the master, so there might have been change causing #1 above.  Ill look into this.

OpenCycleMap
Mapquest
Thunderforest Tiles
CartoDB Positron and Dark Matter
Stamen Design

The above all offer free use of their tiles (and paid if high volume).
And, TBK, none allow self-hosting.
