### ISSUE TITLE
./opentileserver.sh: line 119: ./get-shapefiles.sh: No such file or directory

### ISSUE THREAD

**Issue by jasondinh** [AcuGIS/OpenTileServer#20]
Some changes were made in this commit https://github.com/gravitystorm/openstreetmap-carto/commit/3fd7ddf9bf16faf116e9d66e5a4b7c497c5635fe, the script doesn't work anymore.

**Comment by DavidGhedini** [comment]
Thank you for catching this.  We will update shortly.

**Comment by DavidGhedini** [comment]
This has now been fixed.

**Comment by jasondinh** [comment]
Thanks for the quick fix.
