### ISSUE TITLE
Connection to database failed: FATAL

### ISSUE THREAD

**Issue by CrazyCoder4Carrot** [AcuGIS/OpenTileServer#21]
Error occurred, cleaning up
Connection to database failed: FATAL:  remaining connection slots are reserved for non-replication superuser connections

**Comment by DavidGhedini** [comment]
What is the max_connections value in your conf?

**Comment by CrazyCoder4Carrot** [comment]
I did not set it, just run it on a clean ubuntu 14.04

**Comment by DavidGhedini** [comment]
At point did you get the error? After installation? During?....

**Comment by CrazyCoder4Carrot** [comment]
During, the pbf still there.

**Comment by DavidGhedini** [comment]
Restart PGSQL and try to reload PBF.

**Comment by CrazyCoder4Carrot** [comment]
Thank you for your reply.
