### ISSUE TITLE
Red TIles after running reload-opentileserver

### ISSUE THREAD

**Issue by Unlit4697** [AcuGIS/OpenTileServer#23]
Hi,

When we run reload-opentileserver -add http://download.geofabrik.de....... the script is running sucessfully, however when browsing to the url and the openlayers example we are presented with red tiles. 

No changes were made to the opentileserver.sh script when installed originally. 

is there anything that needs to be changed in the script to match our installation? Or should this just run as is?

Thanks

**Comment by DavidGhedini** [comment]
This was due to the MD5 usage in pg_hba.conf. Renderd couldn't connect ot PG.  This has now been fixed.
