### ISSUE TITLE
reload-script

### ISSUE THREAD

**Issue by spithost** [AcuGIS/OpenTileServer#24]
Hi,

Trying to run the reload-script I ran into the following problem.
When reloading with a new pbf, the script protested, in the HERE-document, that the gis-database wasn't there (it had just dropped it a few lines above) and exited.

After changing the line:
psql -Upostgres ${OSM_DB} <<EOF_CMD
into
psql -Upostgres <<EOF_CMD

the new import started.

Is this a bug in the reload-script? Or should I have done something else...

Regards,
Klaus

**Comment by DavidGhedini** [comment]
Thank you for above.  This has now been fixed.
