### ISSUE TITLE
add data impacts existing region tiles

### ISSUE THREAD

**Issue by bkasodariya** [AcuGIS/OpenTileServer#25]
Hi,

Server setup runs ok. once new data is loaded it affects existing region tiles.

for example
./opentileserver.sh  web bright  http://download.geofabrik.de/europe/great-britain-latest.osm.pbf
It shows Britain ok

below command is used to load/add data
./reload-opentileserver.sh -add http://download.geofabrik.de/north-america/greenland-latest.osm.pbf
./reload-opentileserver.sh -add http://download.geofabrik.de/north-america/us/hawaii-latest.osm.pbf

After above command , Britain tiles affected. Its not coming properly for some zoom in/out which was coming ok before.

Is it required any other steps?

**Comment by DavidGhedini** [comment]
Hi - Do the British tiles eventually render? Did you preload the low res tiles? If you are adding new data sets the database is going to drag accordingly.  Do you have ample memory, SSD, etc...?

**Comment by bkasodariya** [comment]
Thanks for your quick response.
After initial setup British tiles was rendering ok. 
Sorry, didn't get about preload the low res tiles?, I only executed setup script and then data load script to add data.
I am trying on system with AMD 8 Core, 16GB RAM , 400GB HDD, ubuntu14.

**Comment by DavidGhedini** [comment]
Hi -
Are you using PBF "-add"?
If not, it will drop the existing database (where you loaded British Isles).
David

**Comment by bkasodariya** [comment]
yes -add is used in command.

./reload-opentileserver.sh -add http://download.geofabrik.de/north-america/greenland-latest.osm.pbf

**Comment by DavidGhedini** [comment]
Hi -
This should now be resolved.
The issue was using --slim option, which caused a constrain error.
Please use updated script.
Thanks,
David

**Comment by DavidGhedini** [comment]
For Ubuntu 14 this has now been tested and resolved.
