### ISSUE TITLE
Leafletjs Example not working

### ISSUE THREAD

**Issue by ghost** [AcuGIS/OpenTileServer#26]
Hi,

i was installing "Ubuntu-16-Beta.sh" on the 13.03.2017 on an fresh Ubuntu 16.04 LTS.

The OpenLayers Example is working absolutely fine but the Leafletjs Example is not working at all. 

https://ibin.co/3GFTGRyyTqEV.png

I would like to help to fix this issue but as i am new to OpenStreetMap i don't know how. Is there an error log I can have a look into? 

Best Regards
Bud

**Comment by DavidGhedini** [comment]
Hi Bud -
In the page source, check that the url is not 127.0.0.1 or localhost.
It should be your actual IP or host name.
David

**Comment by ghost** [comment]
Wow! Perfect. That's it.
To solve the problem:
nano /var/www/html/leaflet-example.html

remove the 127.0.0.1 AND the IPV6 from Line [14]
BEFORE:
                        L.tileLayer('http://127.0.0.1x.x.x.xx:x:x:x:x:x:x:x/osm_tiles/{z}/{x}/{y}.png', {
AFTER with the IPV4 x.x.x.x Address:
                        L.tileLayer('http://x.x.x.x/osm_tiles/{z}/{x}/{y}.png', {

Thank you for the great script!

**Comment by DavidGhedini** [comment]
You are very welcome. Glad you find it useful.
