### ISSUE TITLE
Problem when adding another map

### ISSUE THREAD

**Issue by SabineMa** [AcuGIS/OpenTileServer#27]
I use your Skript with ubuntu 16. everything works fine with the first import.
After that I'm using the reload Skript with the "-add" attribute. After the Skript finished the first import ist lost and I can see only the last one.
Where is the mistake? Did I something wrong?

**Comment by DavidGhedini** [comment]
Hi -
Are you using PBF "-add"?
If not, it will drop the existing database.
David

**Comment by SabineMa** [comment]
Hi David, 
Yes I do. I also checked it with echo. The variable is set to "yes". If I do it without -add, I see the "create database" etc commands, which don't occur when doing it with "-add".
We check the existence of the data with the openlayers.example html files and also with our Application. We always see only the last created data/country. Tried with ubuntu 14 and 16 with the corresponding files. What can I do to help you, finding the reason for the problem? (Any log files, test/try something ?),
Thank you for helping!

**Comment by SabineMa** [comment]
Hi David,
could you please have look an tell me, what I could send you to help me.
Regards
Sabine

**Comment by DavidGhedini** [comment]
Hi -
I'm having another look at this now.
Thanks,
David

**Comment by tarvr0** [comment]
Hello,
I have the same problem. When I add a map with the “-add” parameter I lost my previous map view.
Is there a fixed or a manual “bypass” for this to resolve this problem?

**Comment by DavidGhedini** [comment]
Hi - Ill have this fixed today. Sorry for the delays.

**Comment by DavidGhedini** [comment]
Hi -
This should now be resolved.
The issue was using --slim option, which caused a constrain error.
Please use updated script.
Thanks,
David

**Comment by SabineMa** [comment]
Hi David,
thanks for having a look. 
The problem isn´t resolved. You removed the —slim option, but the option —append will not work without --slim.
In my opinion it is not possible to add another map to an existing one. I also tried a little, but then I get issues regarding unique keys :-(
But maybe I´m wrong and you´ll find another solution
Sabine

**Comment by tarvr0** [comment]
Hello,
Thanks for the update but now I have a different error
osm2pgsql SVN version 0.88.1 (64bit id space)
osm2pgsql failed due to ERROR: --append can only be used with slim mode!
Ubuntu 16.04 LTS 64 bit

**Comment by DavidGhedini** [comment]
@SabineMa are you on Ubuntu 16 as well?

**Comment by SabineMa** [comment]
Yes I am
David Ghedini <notifications@github.com> schrieb am Mi. 7. Juni 2017 um
14:01:

**Comment by DavidGhedini** [comment]
Ubuntu 14 uses osm2pgsql 0.82 and Ubuntu 16 uses osm2pgsql 0.88.  The versions handle --slim differently.

**Comment by SabineMa** [comment]
Hi David,
I tried with ubuntu 14 and indeed, it works with your fix. 
Do you also have a solution for ubuntu 16?
Regards
Sabine

**Comment by DavidGhedini** [comment]
Nothing yet :( 
We're looking at possible solutions.
In the meantime, I've updated the README accordingly.

**Comment by tarvr0** [comment]
Hello, I tried also with Ubuntu 14 and it's working there.
But showing the maps is very very very slow!
Where can I find some good information to optimize a tile server?

**Comment by DavidGhedini** [comment]
You need SSD and a fair amount of RAM (and tuning PostgreSQL, of course). What are your specs and what is the size of the PBF you imported?

**Comment by tarvr0** [comment]
Hello,
I use in my test environment a SSD disk and 12 GB of RAM memory and have now only belgium.pbf installed.
I see a lot of disk access when I try to open the map.
Any idea?

**Comment by Mrsevic** [comment]
Have a look at https://ircama.github.io/osm-carto-tutorials/tile-server-ubuntu/#install-mapnik-library it helped me a lot in optimizing mine!
