### ISSUE TITLE
Fresh installation script stops.

### ISSUE THREAD

**Issue by AndyW999** [AcuGIS/OpenTileServer#28]
With a fresh Ubuntu installation the script terminates at line 302 

rm /var/www/html/index.html 

because at that point the file does not exist.

rm -f /var/www/html/index.html

Works a lot better!

Also line 304 	

wget -P/var/www/html/ http://cdn.acugis.com/osm-assets/htmls/${p}.html

There was a certificate problem, making it http sorted it.

Can you add Nominatim to the script too ;)

Thanks

Andy.

**Comment by DavidGhedini** [comment]
Is this on Ubuntu 14 or 16?

**Comment by AndyW999** [comment]
Sorry, 16.04.02

**Comment by DavidGhedini** [comment]
Thanks Andy - I will push changes.  We will get Nominatim added as well.
Thanks,
David

**Comment by DavidGhedini** [comment]
The changes have now been committed. Thanks again for finding these.

**Comment by AndyW999** [comment]
Great!

Thanks

Andy.

**Comment by DavidGhedini** [comment]
Hi Andy -
We've added a Nominatim script.
https://github.com/AcuGIS/OpenNameSearch
It's beta but should be fully tested at beginning of week.
Thanks,
David

**Comment by AndyW999** [comment]
Hi David
Will give it a try!
Why only Ubuntu 14 and not 16?
Could it not be combined with the tile server so you only need one of them?
Thanks
Andy.

**Comment by DavidGhedini** [comment]
There was a change in osm2pgsql versions between Ubuntu 14 and 16 and we ran into a wall with Ubuntu 16.  It's certainly possible to use 16 (OSM uses it).  We just gave up (for now).  AFA combining scripts, you can do so, but I think generally people want one or the other.

**Comment by AndyW999** [comment]
No prob, just doing it right now - will let you know if there are any problems I run into!
