### ISSUE TITLE
Out of memory

### ISSUE THREAD

**Issue by Mrsevic** [AcuGIS/OpenTileServer#31]
I recieve the following error whilst trying to appending Italy to a database consisting only of Montenegro. Do you by any chance know the potential solution to this problem?

http://prntscr.com/fmqi6r

Thanks

**Comment by DavidGhedini** [comment]
What is the OS and what are the specs on your server?

**Comment by Mrsevic** [comment]
Same ones as they were in my previous question.

VirtualBox running on 2 cores and 3.5GB of RAM.

I have managed to import it using manual commands and by lowering the cache but Montenegro was completely deleted and I only see the outline of the Italy, when I zoom in, I only see the red tiles. Will try to restart the process.

**Comment by DavidGhedini** [comment]
Sorry, I meant on you on Ubuntu 14 or 16?

**Comment by Mrsevic** [comment]
Ubuntu 14.
