### ISSUE TITLE
Low RAM server

### ISSUE THREAD

**Issue by diskmanti** [AcuGIS/OpenTileServer#32]
I am using a droplet on digitalocean to set up a tile server with your script, but it is not working. My droplet has only 512 MB of RAM, so osm2pgsql can not run properly. It gives a message to try and run it with --node-sparse flag. Can I do something about this or I must use a machine with more ram. I only need to show tiles for Albania, which is a very small country.

 I tried running you script on a VM in virtualbox with 3 GB RAM and it works fine so I know that the issue stands on the RAM capacity.

---

PS: This is the best way I have found to setup a tileserver so good work. 👍

**Comment by DavidGhedini** [comment]
I'm glad you find the script useful.  SSD is only 1/2 of the equation.  I don't think any amount of tuning is going to get even the smallest PBFs loaded and running on 512 MB of RAM.
