### ISSUE TITLE
CORS header issues on Windows Server 2016

### ISSUE THREAD

**Issue by Mrsevic** [AcuGIS/OpenTileServer#33]
I have tried to add   Header set Access-Control-Allow-Origin "*" but still I get the same issues all over again in Chrome.

I am using Ubuntu 14 VM with dual core and 3GB of RAM.

Most of the times tiles render extremely slow, I am not sure why is that the case.

**Comment by DavidGhedini** [comment]
I'm not familiar with Windows at all.
What is the size of the database? 
Have you tuned PostgreSQL?
re: cross-orgin, have you tried: `Header add Access-Control-Allow-Origin "*"` in place of `Header set Access-Control-Allow-Origin "*"`?

**Comment by Mrsevic** [comment]
Yes I have according to the various guides on internet but to no avail. I am not sure about optimal value for VM to be honest.

It is not related to the Windows OS but to any web application in which you place map in.

I will try and let you know thanks!
