### ISSUE TITLE
Debian Stretch version

### ISSUE THREAD

**Issue by lsimedia** [AcuGIS/OpenTileServer#34]
I folks,
I have pseudo-ported your script to Debian Stretch (with tilestache instead of mod_tile and renderd), and I would like to know if my script should/could be integrated in your git project or should I create a new independent project.
My script is quite different than yours, but I "copied" some part of it.
Any feedback welcome.

**Comment by DavidGhedini** [comment]
Hi Isimedia -
It's entirely up to you.
Thanks,
David

**Comment by lsimedia** [comment]
Hi David,
Thanks for your reply.
After some internal discussion we will create a new project called
OpenTileServerDebian (is it ok with you ?).
A new project will be simpler to maintain for us (issue, bug fix, etc.).
We will reference your script, and if you could point debian user to our script, it will be nice.
Grettings from Switzerland
Stephan

**Comment by DavidGhedini** [comment]
Hi Stephen -
We would be happy to point Debian users towards it.
Best,
David

**Comment by sbodmer** [comment]
Hi David, we just created the new project called OpenTileServerDebian.
Have a nice day.
Stephan
