### ISSUE TITLE
cron.daily - osm-update.sh

### ISSUE THREAD

**Issue by lsimedia** [AcuGIS/OpenTileServer#35]
Hi David,

On our clean Ubuntu 14.04 LTS server, "osm-update.sh" script (in "/etc/cron.daily" folder) isn't executed.

If I run command below, "osm-update.sh" isn't displayed : 
run-parts --test --report /etc/cron.daily

If "osm-update.sh" is renamed in to "osm-update" test above is OK and script is executed daily.

Best regards

**Comment by DavidGhedini** [comment]
Thanks - Ill update script.
David
