### ISSUE TITLE
Run scripts in non-english environment.

### ISSUE THREAD

**Issue by bookhankaa** [AcuGIS/OpenTileServer#4]
Add `export LC_ALL=C` at top of scripts.

**Comment by DavidGhedini** [comment]
Honestly not sure of implications.
I will add as comment.

**Comment by bookhankaa** [comment]
http://unix.stackexchange.com/questions/87745/what-does-lc-all-c-do

**Comment by bookhankaa** [comment]
It because I got nothing by running `free -m | grep -i 'mem:'` in "russian" ubuntu.
But it works as `free -m | grep -i 'Память:'`
So, I was need switch output lang into eng.

**Comment by DavidGhedini** [comment]
Thanks for finding this.
I've added to script and will let users decide to uncomment or not.
Thanks,
David
