### ISSUE TITLE
Append Maps Ubuntu 16

### ISSUE THREAD

**Issue by tarvr0** [AcuGIS/OpenTileServer#40]
Is there any change or progress in the script to append maps on Ubuntu 16?

**Comment by DavidGhedini** [comment]
I haven't check recently but will do so this week.

**Comment by tarvr0** [comment]
Any news about the script for append maps?
Anyone tried the script on Ubuntu 17?

**Comment by akuryan** [comment]
I am also intersting - I could not append maps :( on Ubuntu 16

**Comment by tarvr0** [comment]
Hello, Is there any progress to append maps on Ubuntu 16?
Thanks

**Comment by DavidGhedini** [comment]
Will have an update this week when we add Ubuntu 18
