### ISSUE TITLE
City names to English/latin script

### ISSUE THREAD

**Issue by herormo** [AcuGIS/OpenTileServer#41]
I generated tiles for Iraq. The city names are in Arabic. How can I change them to Latin script?

**Comment by DavidGhedini** [comment]
Please see below.
https://help.openstreetmap.org/questions/14805/how-do-i-display-names-in-latin-script
Thanks,
David

**Comment by herormo** [comment]
Thanks David.

I added name:en tag in the openstreetmap-carto.style file and reinstalled the server. The installation run successfully but I can't see the tiles in the browser. I get error 404. 

I run this: sudo - u tile rendered -f -c /usr/local/etc/rendered.conf and I am getting this error:
renderd[3880]: An error occurred while loading the map layer 'default': Postgis Plugin: ERROR:  column "name" does not exist
LINE 5:       way, COALESCE(name, '') AS name,
                            ^
in executeQuery Full sql was: 'SELECT * FROM (SELECT
    way, name, way_pixels,
    COALESCE(wetland, landuse, "natural") AS feature
  FROM (SELECT
      way, COALESCE(name, '') AS name,
      ('landuse_' || (CASE WHEN landuse IN ('forest', 'military') THEN landuse ELSE NULL END)) AS landuse,
      ('natural_' || (CASE WHEN "natural" IN ('wood', 'sand', 'scree', 'shingle', 'bare_rock') THEN "natural" ELSE NULL END)) AS "natural",
      ('wetland_' || (CASE WHEN "natural" IN ('wetland', 'mud') THEN (CASE WHEN "natural" IN ('mud') THEN "natural" ELSE wetland END) ELSE NULL END)) AS wetland,
      way_area/NULLIF(0::real*0::real,0) AS way_pixels
    FROM planet_osm_polygon
    WHERE (landuse IN ('forest', 'military')
      OR "natural" IN ('wood', 'wetland', 'mud', 'sand', 'scree', 'shingle', 'bare_rock'))
      AND way_area > 0.01*0::real*0::real
      AND building IS NULL
    ORDER BY CASE WHEN layer~E'^-?\\d+$' AND length(layer)<10 THEN layer::integer ELSE 0 END, way_area DESC
  ) AS features
) AS landcover_low_zoom LIMIT 0'
  encountered during parsing of layer 'landcover-low-zoom' in Layer at line 502 of '/usr/local/share/maps/style/openstreetmap-carto-3.0.x/osm-carto.xml'
renderd[3880]: An error occurred while loading the map layer 'default': Postgis Plugin: ERROR:  column "name" does not exist
LINE 5:       way, COALESCE(name, '') AS name,
                            ^
in executeQuery Full sql was: 'SELECT * FROM (SELECT
    way, name, way_pixels,
    COALESCE(wetland, landuse, "natural") AS feature
  FROM (SELECT
      way, COALESCE(name, '') AS name,
      ('landuse_' || (CASE WHEN landuse IN ('forest', 'military') THEN landuse ELSE NULL END)) AS landuse,
      ('natural_' || (CASE WHEN "natural" IN ('wood', 'sand', 'scree', 'shingle', 'bare_rock') THEN "natural" ELSE NULL END)) AS "natural",
      ('wetland_' || (CASE WHEN "natural" IN ('wetland', 'mud') THEN (CASE WHEN "natural" IN ('mud') THEN "natural" ELSE wetland END) ELSE NULL END)) AS wetland,
      way_area/NULLIF(0::real*0::real,0) AS way_pixels
    FROM planet_osm_polygon
    WHERE (landuse IN ('forest', 'military')
      OR "natural" IN ('wood', 'wetland', 'mud', 'sand', 'scree', 'shingle', 'bare_rock'))
      AND way_area > 0.01*0::real*0::real
      AND building IS NULL
    ORDER BY CASE WHEN layer~E'^-?\\d+$' AND length(layer)<10 THEN layer::integer ELSE 0 END, way_area DESC
  ) AS features
) AS landcover_low_zoom LIMIT 0'
  encountered during parsing of layer 'landcover-low-zoom' in Layer at line 502 of '/usr/local/share/maps/style/openstreetmap-carto-3.0.x/osm-carto.xml'
renderd[3880]: An error occurred while loading the map layer 'default': Postgis Plugin: ERROR:  column "name" does not exist
LINE 5:       way, COALESCE(name, '') AS name,
                            ^
in executeQuery Full sql was: 'SELECT * FROM (SELECT
    way, name, way_pixels,
    COALESCE(wetland, landuse, "natural") AS feature
  FROM (SELECT
      way, COALESCE(name, '') AS name,
      ('landuse_' || (CASE WHEN landuse IN ('forest', 'military') THEN landuse ELSE NULL END)) AS landuse,
      ('natural_' || (CASE WHEN "natural" IN ('wood', 'sand', 'scree', 'shingle', 'bare_rock') THEN "natural" ELSE NULL END)) AS "natural",
      ('wetland_' || (CASE WHEN "natural" IN ('wetland', 'mud') THEN (CASE WHEN "natural" IN ('mud') THEN "natural" ELSE wetland END) ELSE NULL END)) AS wetland,
      way_area/NULLIF(0::real*0::real,0) AS way_pixels
    FROM planet_osm_polygon
    WHERE (landuse IN ('forest', 'military')
      OR "natural" IN ('wood', 'wetland', 'mud', 'sand', 'scree', 'shingle', 'bare_rock'))
      AND way_area > 0.01*0::real*0::real
      AND building IS NULL
    ORDER BY CASE WHEN layer~E'^-?\\d+$' AND length(layer)<10 THEN layer::integer ELSE 0 END, way_area DESC
  ) AS features
) AS landcover_low_zoom LIMIT 0'
  encountered during parsing of layer 'landcover-low-zoom' in Layer at line 502 of '/usr/local/share/maps/style/openstreetmap-carto-3.0.x/osm-carto.xml'
renderd[3880]: An error occurred while loading the map layer 'default': Postgis Plugin: ERROR:  column "name" does not exist
LINE 5:       way, COALESCE(name, '') AS name,
                            ^
in executeQuery Full sql was: 'SELECT * FROM (SELECT
    way, name, way_pixels,
    COALESCE(wetland, landuse, "natural") AS feature
  FROM (SELECT
      way, COALESCE(name, '') AS name,
      ('landuse_' || (CASE WHEN landuse IN ('forest', 'military') THEN landuse ELSE NULL END)) AS landuse,
      ('natural_' || (CASE WHEN "natural" IN ('wood', 'sand', 'scree', 'shingle', 'bare_rock') THEN "natural" ELSE NULL END)) AS "natural",
      ('wetland_' || (CASE WHEN "natural" IN ('wetland', 'mud') THEN (CASE WHEN "natural" IN ('mud') THEN "natural" ELSE wetland END) ELSE NULL END)) AS wetland,
      way_area/NULLIF(0::real*0::real,0) AS way_pixels
    FROM planet_osm_polygon
    WHERE (landuse IN ('forest', 'military')
      OR "natural" IN ('wood', 'wetland', 'mud', 'sand', 'scree', 'shingle', 'bare_rock'))
      AND way_area > 0.01*0::real*0::real
      AND building IS NULL
    ORDER BY CASE WHEN layer~E'^-?\\d+$' AND length(layer)<10 THEN layer::integer ELSE 0 END, way_area DESC
  ) AS features
) AS landcover_low_zoom LIMIT 0'
  encountered during parsing of layer 'landcover-low-zoom' in Layer at line 502 of '/usr/local/share/maps/style/openstreetmap-carto-3.0.x/osm-carto.xml'

**Comment by DavidGhedini** [comment]
Hi -
Sorry for the delay.
This is likely a better question for the OSM community as I haven't encountered this or worked with translation to Latin alphabet.
Thanks,
David

**Comment by herormo** [comment]
Hi David,

I was able to fix it.

Thanks.
Hero

**Comment by DavidGhedini** [comment]
Hi Hero -
Thanks for letting us know.
Best,
David
