### ISSUE TITLE
Support for EPSG:4326

### ISSUE THREAD

**Issue by tacotown2000** [AcuGIS/OpenTileServer#42]
Is there any chance you would add support for EPSG:4326 (WGS84) to your script?

**Comment by tacotown2000** [comment]
Maybe another way to put it is.. would there be a way to present the data in WGS84 rather than the default of Web Mercator?

**Comment by DavidGhedini** [comment]
Hi -
Sorry for the delay.
Please see below:
https://help.openstreetmap.org/questions/23934/osm-and-4326-projection
Thanks,
David
