### ISSUE TITLE
Ubuntu16.sh fails with osm2pgsql error

### ISSUE THREAD

**Issue by dashwonders** [AcuGIS/OpenTileServer#43]
On a clean DigitalOcean droplet (Ubuntu **16.04.3** **x64**, **16 core**, **64gb**, **1.2TB** SSD), the script fails while using the planet.latest.osm.pbf.  I used:

**_./Ubuntu-16.sh web carto http://planet.openstreetmap.org/pbf/planet-latest.osm.pbf_**

But getting error:

**_Osm2pgsql failed due to ERROR: Connection to database failed: FATAL:  remaining connection slots are reserved for non-replication superuser connections._**

The pbf file size is about 38.8GB.   With about 680gb available on disk after the error, I don't think we were running into disk space issue.  Not sure what I am doing wrong.   The full console grab was beyond the screen buffer, but I am attaching below what was available on screen until the error. 

Please advise.  
Thank you.

[opentileserver_u16_failed_1.2tbssd_64gb.txt](https://github.com/AcuGIS/OpenTileServer/files/1763292/opentileserver_u16_failed_1.2tbssd_64gb.txt)

**Comment by DavidGhedini** [comment]
Hi @dashwonders 
Please check your postgresql.conf and tune accordingly.
This is a PostgreSQL tuning issue, not a script issue.
Thanks,
David

**Comment by dashwonders** [comment]
Thank you, David, for the prompt response -- much appreciated.   I'll look into the PostgreSQL tuning.
