### ISSUE TITLE
/etc/postgresql/9.3/main/pg_hba.conf: No such file or directory

### ISSUE THREAD

**Issue by khangarid** [AcuGIS/OpenTileServer#44]
I'm getting following error on Ubuntu 14.04 
`./opentileserver.sh: line 187: /etc/postgresql/9.3/main/pg_hba.conf: No such file or directory`

**Comment by DavidGhedini** [comment]
Sorry for the long delay - did you make any changes to the script?  It should be installing PGSQL as part of the script.
