### ISSUE TITLE
run error

### ISSUE THREAD

**Issue by prancius** [AcuGIS/OpenTileServer#47]
root@703435:~# ./opentileserver.sh http://download.geofabrik.de/europe/bulgaria-latest.osm.pbf bright
./opentileserver.sh: line 7: syntax error near unexpected token `newline'
./opentileserver.sh: line 7: `<!DOCTYPE html>'

**Comment by DavidGhedini** [comment]
Is the "#" in place on line 7 to comment the line?
Thanks,
David

**Comment by prancius** [comment]
sorry it may problem, close this
