### ISSUE TITLE
error running

### ISSUE THREAD

**Issue by prancius** [AcuGIS/OpenTileServer#48]
root@703435:~# ./opentileserver.sh web carto http://download.geofabrik.de/north-america/us/delaware-latest.osm.pbf
Hit:1 https://download.docker.com/linux/ubuntu xenial InRelease
Hit:2 http://security.ubuntu.com/ubuntu xenial-security InRelease
Hit:3 http://archive.ubuntu.com/ubuntu xenial InRelease
Hit:4 http://archive.ubuntu.com/ubuntu xenial-updates InRelease
Hit:5 http://archive.canonical.com/ubuntu xenial InRelease
Reading package lists... Done
Reading package lists... Done
Building dependency tree
Reading state information... Done
Note, selecting 'libprotobuf-c-dev' instead of 'libprotobuf-c0-dev'
Note, selecting 'libcairo2-dev' instead of 'libcairo-dev'
Note, selecting 'liblua5.1-0-dev' instead of 'liblua5.1-dev'
Package libapache2-mod-php5 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

Package libtiff4-dev is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  libtiff5-dev

Package php5 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

Package libgeotiff-epsg is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'libtiff4-dev' has no installation candidate
E: Package 'libgeotiff-epsg' has no installation candidate
E: Unable to locate package postgresql-9.3-postgis-2.1
E: Couldn't find any package by glob 'postgresql-9.3-postgis-2.1'
E: Couldn't find any package by regex 'postgresql-9.3-postgis-2.1'
E: Package 'php5' has no installation candidate
E: Package 'libapache2-mod-php5' has no installation candidate
root@703435:~#

**Comment by DavidGhedini** [comment]
What is the operating system you are using?

**Comment by prancius** [comment]
ubuntu 16.04

**Comment by DavidGhedini** [comment]
Then you need to use:
https://github.com/AcuGIS/OpenTileServer/blob/master/Ubuntu-16.sh
The script you are using, opentileserver.sh is for Ubuntu 14 only.
Please see README:
https://github.com/AcuGIS/OpenTileServer
