### ISSUE TITLE
Support for Ubuntu 18

### ISSUE THREAD

**Issue by otabekgb** [AcuGIS/OpenTileServer#49]
Will you provide support for Ubuntu 18

**Comment by DavidGhedini** [comment]
Support for Ubuntu 18 will be added this week.

**Comment by DavidGhedini** [comment]
Sorry for the delay - it will be added this coming week.

**Comment by ChiIIerr** [comment]
Looking forward to the implementation! Have Ubuntu 18 already loaded up and ready for this to go for my company. Thanks for the continued support!

**Comment by DavidGhedini** [comment]
Hi -
This has now available:
https://github.com/AcuGIS/OpenTileServer/blob/master/ubuntu-18.sh
