### ISSUE TITLE
Dimensionig the server

### ISSUE THREAD

**Issue by lorenzoperone** [AcuGIS/OpenTileServer#5]
Hi,
I've tried to process the pbf of the entire Italy on a virtual server (the pbf file is about 1,1 GB) and I had a lot of memory issues ([here](https://dl.dropboxusercontent.com/u/4255917/log.zip) is the log).
Could you explain me how much "big" have to be a server to run the process without trouble?
Thanks.
Lorenzo

**Comment by DavidGhedini** [comment]
I've done it with 4 GB of RAM.  The script reads the amount of memory available and uses it.  You can control the memory with the -C switch and the processes for CPU using below:
osm2pgsql --slim -d gis -C 4000 --number-processes 3 /pattToYourItaly.pbf

**Comment by lorenzoperone** [comment]
Hi, 
I've tried again using a server with 56 GB of RAM,
here are the last rows of the log

> Allocating memory for dense node cache
> Allocating dense node cache in one big chunk
> Out of memory for dense node cache, reduce --cache size
> Error occurred, cleaning up

Any ideas?
Thanks.
l.

**Comment by lorenzoperone** [comment]
Hi,
I've changed the osm2pgsql

osm2pgsql_OPTS="--slim -d ${OSM_DB} -C ${C_MEM} --number-processes ${NP} --hstore"

in this way

osm2pgsql_OPTS="--slim --flat-nodes -d ${OSM_DB} -C 8000 --number-processes 3 --hstore"

This time I've used this configuration of the virtual server: 2 core, 14 GB RAM
  and I had this error

> Mid: pgsql, scale=100 cache=8000
> Setting up table: planet_osm_nodes
> NOTICE:  table "planet_osm_nodes" does not exist, skipping
> Setting up table: planet_osm_ways
> NOTICE:  table "planet_osm_ways" does not exist, skipping
> Setting up table: planet_osm_rels
> NOTICE:  table "planet_osm_rels" does not exist, skipping
> 
> Reading in file: gis
> error while opening file gis

I'm quite confused...
Thanks

**Comment by DavidGhedini** [comment]
It looks like the postgresql database tables are not being created.
Can you try on a fresh install?
Does the db and/or tables exist?

**Comment by lorenzoperone** [comment]
Hi David,
it's a clean machine, I'll test the db.
Thanks

**Comment by lorenzoperone** [comment]
Hi,
the DB gis is n the list

> gis       | tile     | UTF8     | en_US.UTF-8 | en_US.UTF-8 | 

but the DB is empty

> public             | geography_columns
>  public             | geometry_columns
>  public             | raster_columns
>  public             | raster_overviews
>  public             | spatial_ref_sys

**Comment by DavidGhedini** [comment]
What OS are you using?

**Comment by lorenzoperone** [comment]
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.4 LTS
Release:    14.04
Codename:   trusty

**Comment by DavidGhedini** [comment]
Did you actually create the HSTORE extension? It was never tested using flat nodes or hstore.  Have you tried running the script without the modifications?

**Comment by lorenzoperone** [comment]
HI,
do you think I should try in a clean machine with this

osm2pgsql_OPTS="--slim -d ${OSM_DB} -C 8000 --number-processes 3 --hstore"

I've not managed postgres, in the clean machine it wasn't installed.
l.

**Comment by DavidGhedini** [comment]
You need to create the HSTORE extension if you are going to use HSTORE.
\c gis
create extension hstore;
I don't use hstore myself, so if you are still having issues, I would try original script without alterations.

**Comment by lorenzoperone** [comment]
Hi David,
HSTORE is in the scrip in your repository...

> osm2pgsql_OPTS="--slim -d ${OSM_DB} -C ${C_MEM} --number-processes ${NP} --hstore"

**Comment by lorenzoperone** [comment]
I've tested, 
but the extension is there...

> postgres=# \connect gis
> You are now connected to database "gis" as user "postgres".
> gis=# create extension hstore;
> ERROR:  extension "hstore" already exists
> gis=#
