### ISSUE TITLE
404 not found

### ISSUE THREAD

**Issue by rijotech** [AcuGIS/OpenTileServer#52]
Running hooks in /etc/ca-certificates/update.d...

done.
done.
Feb 14, 2019 7:18:51 PM org.openstreetmap.osmosis.core.Osmosis run
INFO: Osmosis Version 0.46
Feb 14, 2019 7:18:52 PM org.openstreetmap.osmosis.core.Osmosis run
INFO: Preparing pipeline.
Feb 14, 2019 7:18:52 PM org.openstreetmap.osmosis.core.Osmosis run
INFO: Launching pipeline execution.
Feb 14, 2019 7:18:52 PM org.openstreetmap.osmosis.core.Osmosis run
INFO: Pipeline executing, waiting for completion.
Feb 14, 2019 7:18:52 PM org.openstreetmap.osmosis.core.Osmosis run
INFO: Pipeline complete.
Feb 14, 2019 7:18:52 PM org.openstreetmap.osmosis.core.Osmosis run
INFO: Total execution time: 506 milliseconds.
--2019-02-14 19:18:52--  http://osm.personalwerk.de/replicate-sequences/?Y=2019&m=02&d=14&H=19&i=18&s=52&stream=day
Resolving osm.personalwerk.de (osm.personalwerk.de)... 88.198.11.23, 2a01:4f8:130:23cc::2
Connecting to osm.personalwerk.de (osm.personalwerk.de)|88.198.11.23|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2019-02-14 19:18:52 ERROR 404: Not Found.

**Comment by kaloyan13** [comment]
Fixed in #53 . Tested on Ubuntu 18.

**Comment by rijotech** [comment]
Yeah working now!
