### ISSUE TITLE
Issue if any users on system have tile in the name

### ISSUE THREAD

**Issue by AdamantUK** [AcuGIS/OpenTileServer#54]
I called my machine and default user osmtiler during setup and was wondering why I was having issues.

Went through the script and saw this:
if [ $(grep -c ${OSM_USER} /etc/passwd) -eq 0 ]; then	#if we don't have the OSM user

I would suggest this is changed to:
if [ $(grep -cw ${OSM_USER} /etc/passwd) -eq 0 ]; then	#if we don't have the OSM user

This way we match the whole word for the username 'tile' rather than a partial.

**Comment by AdamantUK** [comment]
Oh, and happy to fix / pull request unless anyone has any thoughts on why this would be a bad idea?

**Comment by DavidGhedini** [comment]
Fixed. Thanks.
