### ISSUE TITLE
Incomplete PBF file.

### ISSUE THREAD

**Issue by AndyW999** [AcuGIS/OpenTileServer#59]
Using Ubuntu-18 -

I had a problem while it was downloading the pbf file.
I re-started the script and it thought the incomplete pbf file was complete and started to process it.
Deleted pbf file and ran it again, all OK.
It does not download the pbf file if it exists, is there a way to check if it is complete?

Also, is there a way to pre-render all the tiles?

Thanks

Andy.

**Comment by DavidGhedini** [comment]
Hi -
Sorry for the delay.
You can pre-render low-zoom (or all tiles if you have the time/space) using below:
https://wiki.openstreetmap.org/wiki/Mod_tile/Setup_of_your_own_tile_server
Regarding checking for complete download, its something we can look at.
Thanks,
David
