### ISSUE TITLE
Leaflet demo doesn't work

### ISSUE THREAD

**Issue by lorenzoperone** [AcuGIS/OpenTileServer#6]
Hi, 
finally we were able to install all Italy using the bright style on Ubuntu 14.04 x64.
The Openlayers demo works but not the Leaflet one, it show only the marker.
[Here](https://dl.dropboxusercontent.com/u/4255917/Schermata%202016-06-09%20alle%2019.53.49.png) is the screenshot.
Bye.

**Comment by DavidGhedini** [comment]
Check the page source - it may be 127.0.0.1 (or localhost) if that is what you installed on.
