### ISSUE TITLE
Dockerfile for testing ideas

### ISSUE THREAD

**Issue by mkcisse** [AcuGIS/OpenTileServer#64]
It would be great to add a docker file. Then, it will ease to install a tile server for testing new ideas. Please see : https://github.com/Overv/openstreetmap-tile-server

**Comment by DavidGhedini** [comment]
Not a Docker/Container fan.  I know they're good for quick set up and testing, but we focus our efforts on production and not Dev/Testing.  It appears your own repo above already does what you are looking for.
