### ISSUE TITLE
Ubuntu 18.04 - libgdal-dev

### ISSUE THREAD

**Issue by Bear4** [AcuGIS/OpenTileServer#65]
Just trying OpenTileServer on Ubuntu 18.04 
(VirtualBox, get Ubuntu-18.04.4-desktop-amd64.iso 2020-04-03 , only install unzip and mc)
with **web** and **bright** options and get an error:
```
root@18:/home/beata/Downloads/OpenTileServer-master# ./opentileserver-ubuntu-18.sh web bright http://download.geofabrik.de/europe/poland/podlaskie-latest.osm.pbf
Reading package lists... Done
Building dependency tree       
Reading state information... Done
software-properties-common is already the newest version (0.96.24.32.12).
0 upgraded, 0 newly installed, 0 to remove and 106 not upgraded.
'universe' distribution component is already enabled for all sources.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
fonts-thai-tlwg is already the newest version (1:0.6.4-2).
fonts-thai-tlwg set to manually installed.
unzip is already the newest version (6.0-21ubuntu1).
bzip2 is already the newest version (1.0.6-8.1ubuntu0.2).
bzip2 set to manually installed.
tar is already the newest version (1.29b-2ubuntu0.1).
tar set to manually installed.
wget is already the newest version (1.19.4-1ubuntu2.2).
wget set to manually installed.
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libgdal-dev : Depends: default-libmysqlclient-dev but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```
Any tips what to do? Seems libgdal-dev is problem.
Thanks for Yours work.
Ps. apt-get upgrade + apt-get update and once again run script - without success - still the same error.

**Comment by kaloyan13** [comment]
I have tried it on Ubuntu 18.04.1 LTS, and it works.
default-libmysqlclient-dev is in main repository, and is installable.

Try to install **default-libmysqlclient-dev**, before running the script.

**Comment by kaloyan13** [comment]
I tried it on Ubuntu 18.04.4, and it still works.
Try running **apt-get dist-upgrade**. I think you have broken packages.

**Comment by Bear4** [comment]
Ok I'll try to download a new package.

**Comment by Bear4** [comment]
With Ubuntu 18.04.04 still no success (several attempts on clean install failed).
But with XUbuntu 16.04 is fine. I have a tile server.
Thanks!

**Comment by Bear4** [comment]
On fresh Ubuntu 18.04.03 
`apt-get install default-libmysqlclient-dev`
Tried again install  ./opentileserver-ubuntu-18.sh ... 
for me it's problem with conflict nodejs and npm. 
```
         nodejs is already the newest version (8.10.0-dfsg-2ubuntu0.4)
         some packages could not be installed 
         ...
         npm: Depedents: node-gyp (>= 0.10.9) but it is not going to be installed
```
When tried hand install npm (aptitude install  npm) then 
```
remove the following packages:
1) default-libmysqlclient-dev [1.0.4 (bionic, now)]
...
```
npm --version  -> 3.5.2
nodejs --version -> v8.10.0

And again run  ./opentileserver-ubuntu-18.sh ...
and again 
```
         nodejs is already the newest version (8.10.0-dfsg-2ubuntu0.4)
         some packages could not be installed 
         ...
         npm: Depedents: node-gyp (>= 0.10.9) but it is not going to be installed
```
I'm wonder what I'm doing wrong, just curious.
