### ISSUE TITLE
Ubuntu 18.04 problem nodejs and npm version (continued issue #65)

### ISSUE THREAD

**Issue by Bear4** [AcuGIS/OpenTileServer#66]
One more time, on fresh Ubuntu 18.04.3 (and 18.04.4)
`apt-get dist-upgrade`
`reboot`
`apt-get install default-libmysqlclient-dev`
Tried again run `./opentileserver-ubuntu-18.sh web bright ... and also web carto`
for me it's problem with conflict nodejs and npm.

         nodejs is already the newest version (8.10.0-dfsg-2ubuntu0.4)
         some packages could not be installed 
         ...
         npm: Depedents: node-gyp (>= 0.10.9) but it is not going to be installed
When tried hand install npm (aptitude install npm) then

```
remove the following packages:
1) default-libmysqlclient-dev [1.0.4 (bionic, now)]
...
```
npm --version -> 3.5.2
nodejs --version -> v8.10.0

And again run `./opentileserver-ubuntu-18.sh web bright ...`
and again

         nodejs is already the newest version (8.10.0-dfsg-2ubuntu0.4)
         some packages could not be installed 
         ...
         npm: Depedents: node-gyp (>= 0.10.9) but it is not going to be installed
I'm wonder what I'm doing wrong, just curious.

**Comment by AndyGodfrey** [comment]
Hi, I'm getting the same error with Ubuntu 18.04. Looks like node-gyp is uninstalled (amongst others) earlier on in the script so even if we manually install them, it doesn't help. I've got around this by using the ubuntu 16 installer and script which works a charm. Have you any luck in getting v18 to work?

**Comment by Bear4** [comment]
Not yet, v18 doesn't work. Last attempt of Ubuntu 18.04 - without GUI. The same effect. I also set up a tile server on Ubuntu 16.04
