### ISSUE TITLE
opentileserver-ubuntu-18 error

### ISSUE THREAD

**Issue by AndyW999** [AcuGIS/OpenTileServer#67]
Hi

When doing a new Ubuntu install there is an error -

src/daemon.c:47:10: fatal error: iniparser/iniparser.h: No such file or directory
 #include <iniparser/iniparser.h>

Looks like some files missing.

Any ideas?

Console log attached.

Thanks

Andy.

[opentileserver-ubuntu-18 error.zip](https://github.com/AcuGIS/OpenTileServer/files/6271669/opentileserver-ubuntu-18.error.zip)

**Comment by Spblizard** [comment]
sudo apt install libiniparser-dev

**Comment by AndyW999** [comment]
Thank you!
