### ISSUE TITLE
links have changed recently - opentileserver-ubuntu-18.sh - i am getting errors - one shown below - next one is naciscdn.org as shown

### ISSUE THREAD

**Issue by tomduffey** [AcuGIS/OpenTileServer#73]
i had a problem with alabama in the us this occurs in carto

i found this info on line to fix it

Changes proposed in this pull request: The link to the ne_110m_admin_0_boundary_lines_land.zip dataset is down due to some issues with hosting. According to the Natural Earth Vector maintainer, you should now use the URLs for S3. The URL and formating of the URL to the new dataset should look like this and appears to be the same file from before: https://naturalearth.s3.amazonaws.com/110m_cultural/ne_110m_admin_0_boundary_lines_land.zip

this problem occurred right after that: this occurs in bright

Resolving naciscdn.org (naciscdn.org)... failed: Name or service not known.
wget: unable to resolve host address ‘naciscdn.org’
 
not sure what the fix is for this one

bh

**Comment by DavidGhedini** [comment]
Merged request.
