### ISSUE TITLE
OpenTileServer/Docker/tile /Dockerfile - syntax

### ISSUE THREAD

**Issue by Bear4** [AcuGIS/OpenTileServer#78]
Is this correct syntax in Dockerfile (line 37)? [http://www.xxx/http//www.xxx]
I check it it's OK.

Configuring OSM Bright
COPY fix_mml.sh /tmp/fix_mml.sh
---> ADD http://www.naturalearthdata.com/http//www.naturalearthdata.com/download/10m/cultural/ne_10m_populated_places.zip /tmp/ne_10m_populated_places.zip

**Comment by Bear4** [comment]
I check it it's OK.

**Comment by DavidGhedini** [comment]
Are you getting an error?
