### ISSUE TITLE
Installation fails - cannot find https://replicate-sequences.osm.mazdermind.de

### ISSUE THREAD

**Issue by AndyW999** [AcuGIS/OpenTileServer#79]
Last bit of terminal - 

etting up default-jre-headless (2:1.11-72build2) ...
Setting up osmosis (0.48.3-1) ...
Processing triggers for man-db (2.10.2-1) ...
Processing triggers for ca-certificates (20230311ubuntu0.22.04.1) ...
Updating certificates in /etc/ssl/certs...
0 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d...

done.
done.
Setting up openjdk-11-jre-headless:amd64 (11.0.20.1+1-0ubuntu1~22.04) ...
update-alternatives: using /usr/lib/jvm/java-11-openjdk-amd64/bin/java to provide /usr/bin/java (java) in auto mode
update-alternatives: using /usr/lib/jvm/java-11-openjdk-amd64/bin/jjs to provide /usr/bin/jjs (jjs) in auto mode
update-alternatives: using /usr/lib/jvm/java-11-openjdk-amd64/bin/keytool to provide /usr/bin/keytool (keytool) in auto mode
update-alternatives: using /usr/lib/jvm/java-11-openjdk-amd64/bin/rmid to provide /usr/bin/rmid (rmid) in auto mode
update-alternatives: using /usr/lib/jvm/java-11-openjdk-amd64/bin/rmiregistry to provide /usr/bin/rmiregistry (rmiregistry) in auto mode
update-alternatives: using /usr/lib/jvm/java-11-openjdk-amd64/bin/pack200 to provide /usr/bin/pack200 (pack200) in auto mode
update-alternatives: using /usr/lib/jvm/java-11-openjdk-amd64/bin/unpack200 to provide /usr/bin/unpack200 (unpack200) in auto mode
update-alternatives: using /usr/lib/jvm/java-11-openjdk-amd64/lib/jexec to provide /usr/bin/jexec (jexec) in auto mode
Oct 30, 2023 10:18:03 PM org.openstreetmap.osmosis.core.Osmosis run
INFO: Osmosis Version 0.48.3
Oct 30, 2023 10:18:03 PM org.openstreetmap.osmosis.core.Osmosis run
INFO: Preparing pipeline.
Oct 30, 2023 10:18:03 PM org.openstreetmap.osmosis.core.Osmosis run
INFO: Launching pipeline execution.
Oct 30, 2023 10:18:03 PM org.openstreetmap.osmosis.core.Osmosis run
INFO: Pipeline executing, waiting for completion.
Oct 30, 2023 10:18:03 PM org.openstreetmap.osmosis.core.Osmosis run
INFO: Pipeline complete.
Oct 30, 2023 10:18:03 PM org.openstreetmap.osmosis.core.Osmosis run
INFO: Total execution time: 278 milliseconds.
--2023-10-30 22:18:03--  https://replicate-sequences.osm.mazdermind.de/?2023-10-30T21:18:03Z&stream=day
Resolving replicate-sequences.osm.mazdermind.de (replicate-sequences.osm.mazdermind.de)... failed: Name or service not known.
wget: unable to resolve host address ‘replicate-sequences.osm.mazdermind.de’
andy@tileserver:~$

**Comment by DavidGhedini** [comment]
What is the OS and which script was used?

**Comment by AndyW999** [comment]
It was Ubuntu 22.01.3 LTD amd64

And the script was opentileserver-ubuntu-22.sh

Just tried opening https://replicate-sequences.osm.mazdermind.de and I get Server not found

As it failed do I have to do a clean ubuntu 22 install to try it again?

Sorry but another question, how can you add another pbf to an existing installation as I remember you had a ubuntu 18 script that would do that but not one for ubuntu 22

**Comment by DavidGhedini** [comment]
Seems to be an issue with his server.  I've logged an issue:
https://github.com/MaZderMind/replicate-sequences/issues/2
The Ubuntu 18 reload script can be used to reload.

**Comment by AndyW999** [comment]
Great, and thanks for the fast response!

When the server comes back can I just restart the script or do I need to do a clean install?

I did ask on the Nominatim Issues page if you could have Nominatim and a Tile Server on the same machine - maybe you could answer?

Thanks...

**Comment by AndyW999** [comment]
Please could you tell me the modifications I need to do to your script so I don't have to wait for the site to come back?

**Comment by DavidGhedini** [comment]
If you want to skip updates, simply create the  ${WORKDIR_OSM}/state.txt file.
If this file is present, it will skip installing updates.

**Comment by AndyW999** [comment]
Thanks!

**Comment by AndyW999** [comment]
Working OK now!

Thanks

Andy.
