### ISSUE TITLE
osm tiles location

### ISSUE THREAD

**Issue by mg2k4** [AcuGIS/OpenTileServer#8]
Hey, Im trying to use your script on some fresh ubuntu 14.04

Everything seems to go ok during install, tho in the end leaflet example is set to load tiles from something like :
L.tileLayer('http://(server_ip)2001:62d0:1007:274e::/osm_tiles/{z}/{x}/{y}.png'
and won't load any tile neither let me access from server_ip/osm_tiles/0/0/0.png

2001:62d0:1007:274e:: is my server Ipv6, I'm running it on some ovh dedicated, how can I fix that ?

Thanks in advance :)

EDIT : My issue is directly related to jasondinh's #9, loading with carto instead of bright will do the trick for me, to load tiles, my ipv6 still is written in examples, just need to remove it

**Comment by DavidGhedini** [comment]
It is expecting an IP v4 address or hostname.

**Comment by mg2k4** [comment]
Yep solved for that thanks,
Now I'm getting stuck on something else ahah
Your script seems to run fine (carto style only) for small data imports, but for bigger imports (whole country) will throw this error :
"could not extend file: wrote only 4096 of 8192 bytes at block HINT:  Check free disk space."

I created a tablespace and changed database name in your script, error thrown is now :
"could not extend file: No space left on device HINT:  Check free disk space."

Sorry for annoying once again ;P

**Comment by DavidGhedini** [comment]
It's a OS error message. Check df -h.
