### ISSUE TITLE
Slow rendering

### ISSUE THREAD

**Issue by AndyW999** [AcuGIS/OpenTileServer#80]
I have got it installed on Ubuntu 22

The PC is a Dell 5500 dual hex Xeon processor with 24GB ram

The rendering is taking forever

I used to use this same setup on an Ubuntu 18 installation and it was really fast

Do you have any suggestions?

**Comment by DavidGhedini** [comment]
You'll need to look at the logs, particularly PostgreSQL.

**Comment by AndyW999** [comment]
OK

**Comment by AndyW999** [comment]
I increased renderd num_threads to 12, this seemed to help

I use offline tiles - download them all and make an ISO to put onto distribution USB sticks

In the past I was using jTileDownloader but this stops after a few hundred tiles, maybe as I now have Gigabit networking

So I am now using the tile downloader from

https://blog.studioblueplanet.net/software/open-street-map-tile-downloader

And all seems well again
