### ISSUE TITLE
bright style not working?

### ISSUE THREAD

**Issue by jasondinh** [AcuGIS/OpenTileServer#9]
I tried `./opentileserver.sh web bright pbf_url` but couldn't get it to work (tile not rendered).

`./opentileserver.sh web carto pbf_url` works fine.

**Comment by DavidGhedini** [comment]
Any errors?

**Comment by jasondinh** [comment]
@DavidGhedini the process seems to run fine without any error. I can run it again and provide the full log in 15-20 minutes.

**Comment by jasondinh** [comment]
@DavidGhedini command: `./opentileserver.sh web bright http://download.geofabrik.de/north-america/us/delaware-latest.osm.pbf`

Output: https://gist.github.com/jasondinh/4dbc7de126d1dd9519f6e9c294a446ad

**Comment by DavidGhedini** [comment]
Have you tried restarting renderd, apache, etc?... I seem to recall having to do this at some point.

**Comment by jasondinh** [comment]
@DavidGhedini I have tried to restart both of them and even do a restart on the server. For `carto` style, it works right after the script is finished running.

**Comment by tgsoverly** [comment]
I can confirm this.  Bright is 404's

**Comment by DavidGhedini** [comment]
This is now fixed.
It was looking for ne_10m_populated_places and we were sending ne_10m_populated_places_simple
